import { useState } from "react";
import { Link, useLocation } from "wouter";
import { ArrowRight, ChevronDown, Instagram, Linkedin, Menu, X } from "lucide-react";
import { trpc } from "@/lib/trpc";

const nav = [
  ["Services", "/services"],
  ["Our work", "/portfolio"],
  ["About", "/about"],
  ["Insights", "/blog"],
  ["Contact", "/contact"],
] as const;

const serviceGroups = [
  { eyebrow: "01 / Brand presence", title: "Make the first impression do more.", links: ["Websites & landing pages", "Personal branding", "Brand identity direction", "Portfolio and profile systems"] },
  { eyebrow: "02 / Visibility & influence", title: "Stay visible for the right reasons.", links: ["Social media management", "Content strategy and production", "Public relations", "Influencer and creator campaigns"] },
];

const articles = [
  ["Personal brand", "Why your online presence should feel like you before you say a word", "A practical guide to turning your point of view, proof, and personality into a recognisable presence."],
  ["Social media", "What makes a social media presence feel alive", "The difference between posting more and building a content rhythm people remember."],
  ["Public relations", "The story is only useful when it travels", "How strong positioning, timely pitching, and consistent visibility work together."],
  ["Websites", "Your website is not a brochure. It is a first conversation.", "How to build a digital home that answers the questions your best clients are already asking."],
  ["Content strategy", "A content plan should give you momentum, not homework", "How to create a sustainable content system that makes showing up feel more natural."],
  ["Brand direction", "The brands people remember make one clear promise", "Why a focused point of view is more powerful than trying to be everything to everyone."],
] as const;

const articleStories: Record<string, { intro: string; sections: [string, string][]; closing: string }> = {
  "Why your online presence should feel like you before you say a word": {
    intro: "Before a client replies to your message, walks into your café, books your service, or shares your work, they have already met the version of you that exists online. They have seen the profile, the website, the images, the language, and the small signals that tell them whether they should stay curious.",
    sections: [["The quiet moment before the decision", "Most people think of an online presence as a collection of platforms. Your website is here. Your profile is there. Your content sits somewhere in between. But your audience does not experience these pieces as separate tasks. They experience one impression, built in seconds and refined over time. That impression should feel like a real introduction, not a template wearing your name."], ["Personality is not a colour palette", "Feeling like you does not mean turning every page into a diary or making every post casual. It means knowing what you notice, what you believe, how you speak, and what you want people to feel after spending time with your work. When those choices repeat with intention, personality becomes recognisable without becoming forced."], ["Proof makes the feeling believable", "A point of view gets attention. Proof builds trust. The projects, decisions, process, clients, details, and lessons behind your work give people something solid to hold on to. Your presence becomes convincing when the emotional promise and the practical evidence are telling the same story."], ["The presence that stays after the scroll", "The goal is not to impress everyone who passes by. It is to make the right people feel that they have found something specific. When your online presence sounds like you before you say a word, the first conversation begins with recognition instead of explanation."]],
    closing: "Your presence should not ask you to become a louder version of someone else. It should make the most valuable parts of your real work easier to see.",
  },
  "What makes a social media presence feel alive": {
    intro: "A social media presence feels alive when it feels connected to something happening in the real world. Not busy for the sake of being busy. Not polished until there is nothing human left. Alive means there is a point of view, a rhythm, and a reason to come back.",
    sections: [["Posting is not the same as participating", "A calendar can tell you what goes out on Tuesday. It cannot, by itself, tell you why anyone should care. A living presence responds to the season, the audience, the work in progress, the questions people are asking, and the moments that reveal what the brand is really like."], ["Give every format a job", "A strong social system makes room for different kinds of attention. One post can introduce an idea. Another can show the process behind it. A short video can create energy. A considered caption can create trust. When every format does the same job, the feed becomes repetitive. When each format has a role, the whole presence starts to breathe."], ["Consistency is a form of care", "People do not need perfection from a brand, but they do need a sense that someone is paying attention. A consistent rhythm tells the audience that the work is active, the promise is real, and there will be another useful reason to return. Consistency is not publishing without thought; it is making thought repeatable."], ["Leave room for a human voice", "The strongest brands still sound like people. They can be clear without being stiff, strategic without being distant, and recognisable without repeating the same phrase forever. The audience should feel that there is a mind behind the message and a real intention behind the invitation to engage." ]],
    closing: "A social presence becomes memorable when it stops performing activity and starts expressing a living point of view.",
  },
  "The story is only useful when it travels": {
    intro: "A story can be true, beautiful, and important, and still remain too close to home. Public relations begins with the question of how that story travels: who needs to hear it, why they might care, and what makes the moment worth sharing now.",
    sections: [["Start with the reason to care", "A press release is not a reason. A reason is the change, tension, insight, or human detail that makes a wider audience lean closer. The work becomes easier to pitch when the story is shaped around something larger than the announcement itself."], ["Relevance is more powerful than reach", "Being mentioned everywhere is not the same as being understood by the right people. The most useful media conversations are connected to the audience, culture, category, or moment where your work belongs. Relevance gives visibility a longer life because it reaches people who have a reason to remember it."], ["Make the story easy to carry", "Editors, journalists, creators, and partners are busy. They need a clear angle, useful context, strong language, and the confidence that the story will hold up beyond the first line. Good PR gives people a story they can understand, explain, and make their own without losing the truth at the centre."], ["Visibility becomes credibility over time", "One feature can create a moment. A thoughtful pattern of relevant stories creates recognition. That is why PR works best when it is connected to the larger brand: the website, the social presence, the expertise, and the proof should all support the same public understanding." ]],
    closing: "The story is only useful when it travels far enough to meet the people who were already looking for what you do.",
  },
  "Your website is not a brochure. It is a first conversation.": {
    intro: "A potential client does not arrive at your website with unlimited patience. They arrive with a question, a need, or a small spark of curiosity. The page has one job before anything else: make it easy for them to understand why staying is worth their time.",
    sections: [["The first screen sets the emotional temperature", "Before someone reads every service, they want to know whether this is for them. A clear opening tells them what you do, who you help, and what kind of difference you are interested in making. The visual direction then confirms the feeling of the words. Together, they create the first answer."], ["Structure is a form of hospitality", "Good navigation is not just a technical detail. It is a way of respecting the person on the other side of the screen. They should be able to find the work, understand the offer, see the proof, and know what to do next without solving a puzzle."], ["Specificity makes trust easier", "The most convincing websites do not hide behind broad claims. They describe the kind of work, the way it happens, the decisions it supports, and the people it is designed for. Specific language gives the right visitor a place to recognise themselves."], ["The next step should feel natural", "A website should not pressure people into a decision they are not ready to make. It should make the next step clear: ask a question, start a project, book a conversation, or keep reading. Clarity is what turns interest into movement." ]],
    closing: "The best website does not simply display your work. It begins the relationship your work deserves.",
  },
  "A content plan should give you momentum, not homework": {
    intro: "Many content plans fail before the first post because they are built like assignments. Too many formats, too many deadlines, and no clear connection to the reason the brand needs to show up. A useful content plan should make the next good idea easier to find.",
    sections: [["Start with the conversations you want to earn", "Content becomes easier when you know what you want to be known for. Instead of beginning with a list of trending formats, begin with the questions your audience asks, the problems you solve, the perspective you bring, and the proof you can share."], ["Build pillars that leave room to breathe", "A content pillar should guide you, not trap you. It gives the brand a few dependable territories to return to while leaving enough room for new work, new observations, client stories, behind-the-scenes moments, and timely ideas."], ["Create once, carry the idea further", "One strong thought can become a post, a short video, a newsletter paragraph, a conversation starter, and a deeper page on the website. This is not repetition without imagination. It is giving a good idea more than one chance to meet the right person."], ["Make the system fit the people using it", "The most sophisticated plan is useless if nobody can maintain it. A sustainable system accounts for the time, tools, people, and energy available. Momentum comes from a plan that can survive a busy week and still feel worth returning to." ]],
    closing: "The right content system does not make you feel constantly behind. It gives your thinking somewhere to go.",
  },
  "The brands people remember make one clear promise": {
    intro: "In a crowded category, the instinct is often to add more. More services, more words, more colours, more reasons to choose you. But memory rarely works through accumulation. The brands people remember usually make one clear promise and keep finding different ways to prove it.",
    sections: [["A promise is not a slogan", "A brand promise is the experience people can expect from you. It shapes the way you describe the work, the way you make decisions, the way you respond, and the way your audience feels after the interaction. It has to be useful inside the business before it can be believable outside it."], ["Focus creates distinction", "You do not become more valuable by trying to be the answer for everyone. Focus helps the right people identify the fit faster. It gives your content a centre, your website a clearer structure, and your team a better filter for deciding what belongs."], ["Repetition is how recognition is built", "A clear promise needs time. It should appear in the language, the visual cues, the stories, the proof, and the small details that make the brand feel like itself. Repetition is not a lack of creativity; it is how meaning becomes familiar."], ["Let the promise be tested by the work", "The strongest brand direction is practical. It changes what you make, what you say yes to, what you show, and what you improve. When the public promise and the lived experience agree, the brand stops feeling like a campaign and starts feeling like a relationship." ]],
    closing: "A focused brand does not say less because it has less to offer. It says the most important thing clearly enough to be remembered.",
  },
};

const workItems = [
  ["Brand presence", "Zumorrud", "A considered brand and digital presence built to make Zumorrud easier to understand, remember, and choose.", "Strategy · Website · Social"],
  ["Growth system", "Neurovia Nexus Private Limited", "A clearer communications system for a company with ambitious work and a need to translate its value into a stronger public presence.", "Positioning · Content · Visibility"],
  ["Retail presence", "Fowalk Footwear", "A footwear brand story designed to connect product, everyday style, and the confidence that makes a pair worth coming back to.", "Brand story · Social · Campaigns"],
] as const;

const workStories: Record<string, { kicker: string; headline: string; overview: string; challenge: string; approach: string; outcome: string; services: string[] }> = {
  Zumorrud: {
    kicker: "Brand presence / Selected work",
    headline: "Making Zumorrud easier to discover, understand, and remember.",
    overview: "Zumorrud came to the work with the kind of opportunity many growing businesses know well: the work had its own character, but the public-facing story needed to catch up. Our role was to bring that character into a clearer, more consistent presence across the places where people first encounter the company.",
    challenge: "The challenge was not simply to make the brand look better. It was to make the value of Zumorrud easier to read at a glance, while keeping the personality that makes the company feel human. The brand needed a sharper introduction, a more confident digital home, and content that could keep the conversation moving after the first impression.",
    approach: "We shaped the work around a simple system: clarify the central story, give the visual language room to breathe, and create repeatable content directions rather than isolated posts. The website and social touchpoints were treated as one connected experience, with the same tone, hierarchy, and cues carrying through from the first scroll to the next conversation.",
    outcome: "The result was a more coherent public presence for Zumorrud: clearer in its introduction, more consistent in its expression, and better prepared to turn attention into genuine interest. Instead of asking every touchpoint to explain the company from scratch, the new system gave the brand a recognisable way to show up and build familiarity over time.",
    services: ["Brand positioning", "Website direction", "Social content system", "Ongoing visibility"],
  },
  "Neurovia Nexus Private Limited": {
    kicker: "Growth system / Selected work",
    headline: "Turning complex value into a public story people can follow.",
    overview: "Neurovia Nexus Private Limited operates in a space where the work can be meaningful and ambitious, but the story can quickly become difficult to communicate. We worked on the layer between the company’s capability and the audience’s understanding: the language, structure, and visual direction that make a serious business feel clear without flattening what makes it different.",
    challenge: "The central challenge was translation. Strong work can still be overlooked when the website, content, and public messaging speak in separate voices. Neurovia Nexus needed a clearer way to introduce its value, organise its ideas, and build confidence with the people it wanted to reach.",
    approach: "We built the communications around a stronger point of view and a more deliberate rhythm. The work connected positioning with content planning, turned important ideas into accessible narratives, and created a foundation that could support future campaigns, partnerships, and conversations. Every piece was designed to answer the same question: why does this matter, and why now?",
    outcome: "Neurovia Nexus left with a more legible public presence and a communications foundation that could grow with the company. The work made the brand easier to enter, easier to explain, and more equipped to build recognition through consistent, useful visibility rather than one-off noise.",
    services: ["Positioning direction", "Narrative development", "Content strategy", "Public visibility"],
  },
  "Fowalk Footwear": {
    kicker: "Retail presence / Selected work",
    headline: "Giving Fowalk Footwear a story that feels as good as the product.",
    overview: "Fowalk Footwear is in a category where people make quick decisions with their eyes before they make them with their feet. We worked on the story around the product: the visual world, the everyday context, and the small details that help a footwear brand feel relevant, dependable, and worth remembering.",
    challenge: "The opportunity was to move beyond product-only communication. Footwear is functional, but the strongest brands also sell a feeling: confidence on the move, a dependable choice for everyday life, or a point of view about personal style. Fowalk needed a way to show both the product and the life around it.",
    approach: "We developed a content and campaign direction that put the shoes into real moments instead of treating each product as an isolated catalogue item. Product storytelling, social formats, and campaign language worked together to make the brand more immediate, while keeping the focus on wearability, character, and the reasons someone would choose Fowalk again.",
    outcome: "The result was a more inviting brand story for Fowalk Footwear: product-led, but never product-only. The company gained a clearer platform for social communication and campaigns, giving future launches and everyday content a consistent world to build from.",
    services: ["Brand story", "Campaign direction", "Social content", "Product visibility"],
  },
};

const slugify = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

export default function PublicSite({ page = "home", slug }: { page?: string; slug?: string }) {
  const [, setLocation] = useLocation();
  const [menuOpen, setMenuOpen] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const isHome = page === "home";
  const title = page === "services" ? "Ideas, identity, and visibility — made to move." : page === "portfolio" ? "Work that gives good brands somewhere to go." : page === "case-studies" ? "The thinking behind the work." : page === "blog" ? "Notes on brands, culture, and being seen." : page === "about" ? "A media agency for people with something to say." : page === "roi" ? "Build a presence that earns its place." : page === "contact" ? "Let’s make your next move visible." : page === "free-audit" ? "Find the gaps in your public presence." : "Build a presence people remember.";

  return <div className="public-site">
    <header className="public-header"><Link href="/" className="public-brand"><img className="public-logo-image" src="/assets/earden-media-logo.webp" alt="EARDEN MEDIA" /></Link><nav className={`public-nav ${menuOpen ? "public-nav--open" : ""}`}>{nav.map(([label, href]) => <Link key={href} href={href} onClick={() => setMenuOpen(false)}>{label}</Link>)}<Link href="/contact" className="public-nav-cta" onClick={() => setMenuOpen(false)}>Start a conversation <ArrowRight size={14} /></Link></nav><button className="public-menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></header>

    {isHome ? <>
      <section className="public-hero"><div className="public-eyebrow">MEDIA AGENCY · BRAND · SOCIAL · PR</div><h1>Build a presence.<br /><i>Make it matter.</i><br />Be remembered.</h1><p>Erden Media helps ambitious people and brands show up with a sharper identity, stronger content, and the visibility to move the room.</p><div className="public-actions"><Link className="public-button public-button--dark" href="/contact">Start a project <ArrowRight size={15} /></Link><Link className="public-button" href="/services">See what we do <ArrowRight size={15} /></Link></div><div className="public-positioning"><span>OUR APPROACH</span><strong>We connect the story, the look, the content, and the right audience.</strong></div></section>
      <MetricBand />
      <section className="public-proofline"><span>Built for brands with something to say</span><div className="proof-names"><b>WEBSITES</b><b>PERSONAL BRANDS</b><b>SOCIAL</b><b>PR</b><b>CONTENT</b><b>CAMPAIGNS</b></div></section>
      <ServicesSection />
      <section className="public-section public-difference"><div className="section-kicker">03 · Why Erden Media</div><h2>Good work deserves<br /><i>to be seen properly.</i></h2><div className="difference-grid">{[["01", "A point of view", "We help you find the idea, tone, and visual language that feels unmistakably yours."], ["02", "A presence with rhythm", "From the website to the weekly post, every touchpoint works as part of the same story."], ["03", "Visibility with intent", "PR, creators, and campaigns built to put your name in the right conversations."], ["04", "A partner in the room", "Strategy and execution together, without making you translate your ambition into a brief."]].map(([n, t, d]) => <div key={n} className="difference-card"><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section>
      <FeaturedSection />
      <ProcessSection />
      <NotesSection />
      <FaqSection openFaq={openFaq} setOpenFaq={setOpenFaq} />
      <ContactSection />
    </> : page === "contact" ? <ContactSection /> : page === "portfolio-detail" ? <WorkDetailPage slug={slug || ""} /> : page === "blog-detail" ? <ArticleDetailPage slug={slug || ""} /> : page === "about" ? <AboutPage /> : <InteriorPage page={page} title={title} />}

    <footer className="public-footer"><div className="public-footer-top"><div className="public-footer-brand"><div className="public-brand"><img className="public-logo-image public-logo-image--footer" src="/assets/earden-media-logo.webp" alt="EARDEN MEDIA" /></div><p>Ideas, identity, and visibility for people and brands with something to say.</p></div><div className="public-footer-column"><span className="public-footer-label">Explore</span><div className="footer-links">{nav.slice(0, 5).map(([label, href]) => <Link key={href} href={href}>{label}</Link>)}</div></div><div className="public-footer-column"><span className="public-footer-label">Contact</span><a href="mailto:support@eardenmedia.site">support@eardenmedia.site</a><a href="mailto:info@eardenmedia.site">info@eardenmedia.site</a><a href="tel:+919864382265">+91 9864-382-265</a><div className="public-footer-socials"><a className="public-footer-social" href="https://instagram.com/eardenmedia" target="_blank" rel="noreferrer" aria-label="Open EARDEN MEDIA on Instagram"><Instagram size={17} aria-hidden="true" /></a><span className="public-footer-social public-footer-social--inactive" title="LinkedIn coming soon" aria-label="LinkedIn coming soon"><Linkedin size={17} aria-hidden="true" /></span></div></div><div className="public-footer-column"><span className="public-footer-label">Visit</span><span>Dimoruguri, 782003</span><span>Nagaon, Assam</span><span>Mon–Fri · 11:00 AM–9:00 PM</span></div></div><div className="public-footer-bottom"><span>© 2026 EARDEN MEDIA</span><span>Built for better visibility.</span></div></footer>
  </div>;
}

function MetricBand() { return <section className="metric-band"><div><strong>06</strong><span>ways to show up</span></div><div><strong>04</strong><span>core disciplines</span></div><div><strong>01</strong><span>clear point of view</span></div><div><strong>∞</strong><span>room to grow</span></div></section>; }
function ServicesSection() { return <section className="public-section"><div className="section-kicker">02 · What we manage</div><div className="section-title-row"><h2>One story.<br /><i>Many ways to show up.</i></h2><Link href="/services" className="text-link">All services <ArrowRight size={14} /></Link></div><div className="service-grid">{serviceGroups.map((group) => <div className="service-card" key={group.eyebrow}><span className="service-eyebrow">{group.eyebrow}</span><h3>{group.title}</h3><div>{group.links.map((link) => <Link href="/services" key={link}>{link}<ArrowRight size={14} /></Link>)}</div></div>)}</div></section>; }
function FeaturedSection() { return <section className="public-section featured-section"><div className="section-kicker">04 · Selected work</div><div className="featured-grid"><div><h2>Make the brand feel as good as the work behind it.</h2><p>We bring strategy, design, content, social, and PR together so the public sees the same confidence you bring to the work.</p><Link href="/portfolio" className="text-link">See selected work <ArrowRight size={14} /></Link></div><div className="featured-visual"><img src="/assets/agencyos-campaign-collage.webp" alt="Illustrative campaign planning collage" /><div><strong>01</strong><span>work in<br />motion</span></div></div></div></section>; }
function ProcessSection() { return <section className="public-section process-section"><div className="section-kicker">05 · How we work</div><h2>From first thought<br /><i>to public presence.</i></h2><div className="process-grid">{[["01", "Listen", "Understand the ambition, the audience, and the story only you can tell."], ["02", "Shape", "Turn the raw idea into a clear brand direction, content system, and campaign plan."], ["03", "Make", "Build the website, shoot the content, run the socials, and create the things people see."], ["04", "Amplify", "Put the work into the right conversations through social, PR, creators, and partnerships."]].map(([n, t, d]) => <div key={n} className="process-item"><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section>; }
function NotesSection() { return <section className="public-section notes-section"><div className="section-title-row"><div><div className="section-kicker">06 · Insights</div><h2>Ideas for being seen<br /><i>without shouting.</i></h2></div><Link href="/blog" className="text-link">All notes <ArrowRight size={14} /></Link></div><div className="notes-grid">{articles.map(([category, title, desc]) => <Link href={`/blog/${slugify(title)}`} className="note-card" key={title}><span>{category}</span><h3>{title}</h3><p>{desc}</p><small>08 min read <ArrowRight size={13} /></small></Link>)}</div></section>; }
function FaqSection({ openFaq, setOpenFaq }: { openFaq: number | null; setOpenFaq: (value: number | null) => void }) { const faqs = [["What kind of work do you take on?", "We work across websites, personal branding, social media management, content, PR, influencer campaigns, and launch moments."], ["Who do you work with?", "Founders, artists, creators, cafés, restaurants, growing brands, and teams with a point of view they want to make visible."], ["Can you help with both strategy and execution?", "Yes. We can shape the direction and then make the website, content, social rhythm, and PR activity that brings it to life."], ["How do we get started?", "Send us a note about what you are building or changing. We will come back with the clearest next step, whether that is a conversation, audit, or project outline."]]; return <section className="public-section faq-section"><div className="section-kicker">07 · Questions</div><h2>A few things<br /><i>you might want to know.</i></h2><div className="faq-list">{faqs.map(([q, a], index) => <div className={`faq-item ${openFaq === index ? "faq-item--open" : ""}`} key={q}><button onClick={() => setOpenFaq(openFaq === index ? null : index)}><span>{q}</span><ChevronDown size={17} /></button>{openFaq === index && <p>{a}</p>}</div>)}</div></section>; }
function ContactSection() {
  const createInquiry = trpc.agency.createInquiry.useMutation();
  const [submitted, setSubmitted] = useState(false);
  const [error, setError] = useState("");
  const [form, setForm] = useState(() => ({ name: "", email: "", company: "", service: (typeof window !== "undefined" && new URLSearchParams(window.location.search).get("service")) || "Website / landing page", message: "" }));
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  return <section className="public-contact"><div><div className="section-kicker">08 · Start here</div><h2>Have something worth<br /><i>putting into the world?</i></h2><p>Tell us what you are building, changing, launching, or becoming. We will help you turn it into a presence people can feel.</p>{submitted && <div className="form-success">Thanks — your enquiry is with the Erden Media team. We’ll be in touch soon.</div>}{error && <div className="form-error">{error}</div>}</div><form onSubmit={(event) => { event.preventDefault(); setError(""); setSubmitted(false); createInquiry.mutate({ ...form, company: form.company || undefined, source: "contact" }, { onSuccess: () => { setSubmitted(true); setForm({ name: "", email: "", company: "", service: "Website / landing page", message: "" }); }, onError: (mutationError) => setError(mutationError.message || "We could not send your enquiry. Please try again.") }); }}><label>Name<input required value={form.name} onChange={(event) => update("name", event.target.value)} placeholder="Your name" /></label><label>Work email<input required type="email" value={form.email} onChange={(event) => update("email", event.target.value)} placeholder="you@brand.com" /></label><label>Company or brand<input value={form.company} onChange={(event) => update("company", event.target.value)} placeholder="Your brand, studio, or name" /></label><label>What do you need?<select value={form.service} onChange={(event) => update("service", event.target.value)}><option>Website / landing page</option><option>Personal branding</option><option>Social media management</option><option>Content strategy and production</option><option>Public relations</option><option>Influencer campaign</option><option>Custom service</option></select></label><label>Tell us a little more<textarea required minLength={10} value={form.message} onChange={(event) => update("message", event.target.value)} placeholder="What are you building, changing, launching, or becoming?" /></label><button className="public-button public-button--dark" type="submit" disabled={createInquiry.isPending}>{createInquiry.isPending ? "Sending…" : "Send the request"} <ArrowRight size={15} /></button></form></section>;
}
function AboutPage() {
  const services = [
    ["01", "Websites & landing pages", "Your website is often the first serious conversation a potential client has with your brand. We shape that conversation from the opening line to the final click. We clarify the story, organise the information, direct the visual language, and build a digital home that feels credible, easy to navigate, and unmistakably yours."],
    ["02", "Personal branding", "People do business with clarity, conviction, and trust. We help founders, artists, creators, and professionals turn their experience and point of view into a personal brand that can travel across a profile, portfolio, speaking opportunity, launch, or long-term body of work. The goal is not to perform a personality; it is to make the real one easier to recognise."],
    ["03", "Social media management", "Social media becomes valuable when it stops feeling like a list of obligations. We build a rhythm around your message, your audience, and the moments that deserve attention. From content pillars and calendars to captions, creative direction, publishing, and review, we help you show up consistently without sounding repetitive or losing the human voice behind the brand."],
    ["04", "Content strategy & production", "Good content is not just more content. It is the right idea, shaped for the right format, at the right time. We create content systems that connect strategy with execution: campaign concepts, editorial direction, short-form storytelling, visual references, copy, shoots, and repeatable formats your team can actually use. Every piece should have a job, and every job should add to the larger story."],
    ["05", "Public relations", "Visibility is more meaningful when it arrives in the right conversations. We help shape the story worth sharing, prepare the language around it, identify relevant media angles, and support thoughtful outreach. PR is not about making noise everywhere; it is about making the right people curious, giving them a clear reason to care, and building credibility one relevant conversation at a time."],
    ["06", "Influencer & creator campaigns", "The strongest creator collaborations feel like a natural meeting between a brand and a point of view people already trust. We help define the campaign idea, identify the right kind of creator, shape the brief, coordinate deliverables, and keep the work aligned with the brand without sanding away the creator’s voice."],
    ["07", "Brand identity direction", "When the identity is right, the brand becomes easier to remember before it needs to explain itself. We help align tone, visual cues, messaging, content references, and the small details that make a business feel considered. This is the connective tissue between what you mean, how you look, and how people experience you."],
    ["08", "Campaigns & launches", "A launch is a moment, but a strong launch also creates the next chapter. We bring the story, creative direction, content, social, PR, and creator thinking into one coordinated campaign plan. That gives the audience a clear way in and gives your team a practical way to move from first announcement to sustained attention."],
  ];
  return <main className="about-page">
    <section className="about-hero"><div className="section-kicker">ERDEN MEDIA / ABOUT</div><h1>Because good work deserves a <i>real chance</i> to be seen.</h1><p className="about-hero-lede">EARDEN MEDIA exists for the moment when you know there is something worth building, but the world has not understood it yet.</p><Link href="/contact" className="public-button public-button--dark">Tell us what you are building <ArrowRight size={15} /></Link></section>
    <section className="about-story"><div className="section-kicker">01 · The reason we exist</div><div className="about-story-grid"><div><h2>Every ambitious brand starts with a feeling.</h2></div><div><p>It is the feeling that the work could go further. That the idea could reach more people. That the business, the talent, the product, or the personal point of view deserves to be understood beyond the people who already know it.</p><p>But good work does not automatically become a good story. A strong service can look ordinary when the website is unclear. A remarkable person can disappear into a generic profile. A meaningful business can struggle to be remembered when every platform speaks in a different voice.</p><p>That is where we come in. EARDEN MEDIA is the layer between what you are capable of and what the public can feel. We find the thread, give it shape, and help it travel through the places where people discover, evaluate, and choose brands.</p></div></div></section>
    <section className="about-belief"><div className="section-kicker">02 · What we believe</div><blockquote>“The goal is not to look louder. The goal is to become clearer, more recognisable, and easier to choose.”</blockquote><div className="about-belief-grid"><div><strong>Clarity before decoration.</strong><p>Before we choose the colour, format, or channel, we ask what the audience needs to understand and remember.</p></div><div><strong>Consistency creates trust.</strong><p>A website, post, pitch, campaign, and conversation should feel like they belong to the same world.</p></div><div><strong>Visibility should have intent.</strong><p>We do not chase attention for its own sake. We build presence around the people, opportunities, and conversations that matter.</p></div></div></section>
    <section className="about-services"><div className="section-kicker">03 · What we do</div><h2>One partner for the parts of your presence people actually experience.</h2><p className="about-section-lede">You should not have to explain your business five different ways to five different specialists. Our work brings strategy, design, content, social, PR, and campaigns into one connected operating system for your public presence.</p><div className="about-service-list">{services.map(([number, title, description]) => <article key={number} className="about-service-item"><span>{number}</span><div><h3>{title}</h3><p>{description}</p></div></article>)}</div></section>
    <section className="about-fit"><div className="section-kicker">04 · Who we are for</div><h2>For the café finding its people. The founder finding their voice. The company ready for its next room.</h2><p>We work with cafés and restaurants, artists and musicians, creators and influencers, founders, growing companies, and brands with something specific they want to be known for. You do not need to have everything figured out before you come to us. You need a real ambition, an honest starting point, and the willingness to make the presence match the potential.</p><p>Some clients come with a blank page. Others come with years of work and a public presence that no longer reflects where they are going. Both are good places to begin.</p></section>
    <section className="about-process"><div className="section-kicker">05 · How it feels to work with us</div><div className="about-process-grid"><div><span>01</span><h3>We listen for the real story.</h3><p>We start with your ambition, your audience, your proof, and the things you do not want to sound like.</p></div><div><span>02</span><h3>We turn it into a clear direction.</h3><p>You get a point of view that helps decisions become easier across the website, content, social, and campaigns.</p></div><div><span>03</span><h3>We make the work people see.</h3><p>We move from strategy into words, visuals, formats, pages, pitches, and systems that can live in the real world.</p></div><div><span>04</span><h3>We keep the presence moving.</h3><p>Because the strongest brands are not built in one dramatic moment. They become familiar through thoughtful repetition.</p></div></div></section>
    <section className="about-close"><div className="section-kicker">06 · The next step</div><h2>If you have been waiting for the right time to show up properly, this is your sign.</h2><p>Tell us what you are building, changing, launching, or becoming. We will help you see the clearest next move and shape the presence to carry it.</p><Link href="/contact" className="public-button public-button--dark">Start a conversation <ArrowRight size={15} /></Link></section>
  </main>;
}

function InteriorPage({ page, title }: { page: string; title: string }) {
  const serviceItems = serviceGroups.flatMap((group) => group.links);
  const items = page === "services" ? serviceItems : page === "blog" ? articles.map((article) => article[1]) : page === "portfolio" ? workItems.map((item) => item[1]) : ["Websites and landing pages", "Personal branding", "Social media management", "Content strategy and production", "Public relations", "Influencer campaigns"];
  return <main className="public-interior"><div className="section-kicker">ERDEN MEDIA / {page.replaceAll("-", " ")}</div><h1>{title}</h1><p className="interior-lede">A media agency for brands, founders, artists, and teams who want to look sharper, sound clearer, and be seen by the right people.</p><div className="interior-grid">{items.map((item, index) => { const href = page === "blog" ? `/blog/${slugify(item)}` : page === "portfolio" ? `/portfolio/${slugify(item)}` : "/contact"; const description = page === "portfolio" ? workItems.find((work) => work[1] === item)?.[2] : page === "blog" ? articles.find((article) => article[1] === item)?.[2] : "See how we turn this part of your public presence into something clear, considered, and memorable."; return <div className="interior-card" key={item}><span>{String(index + 1).padStart(2, "0")}</span><h2>{item}</h2><p>{description}</p><Link href={page === "services" ? `/contact?service=${encodeURIComponent(item)}` : href} className="text-link">{page === "portfolio" ? "View project" : page === "blog" ? "Read note" : "Talk to us"} <ArrowRight size={14} /></Link></div>; })}{page === "services" && <div className="interior-card interior-card--custom"><span>07</span><h2>Something else in mind?</h2><p>Tell us what you are building, launching, or changing. We can shape a custom mix of strategy, design, content, social, and PR around it.</p><Link href="/contact?service=Custom service" className="text-link">Build a custom service <ArrowRight size={14} /></Link></div>}</div></main>;
}

function WorkDetailPage({ slug }: { slug: string }) {
  const work = workItems.find((item) => slugify(item[1]) === slug) || workItems[0];
  const story = workStories[work[1]] || workStories.Zumorrud;
  return <main className="public-interior detail-page">
    <div className="section-kicker">ERDEN MEDIA / {story.kicker}</div>
    <h1>{story.headline}</h1>
    <p className="interior-lede">{story.overview}</p>
    <div className="detail-meta"><span>{work[0]}</span><span>{work[3]}</span></div>
    <div className="detail-story">
      <h2>The brief</h2>
      <p>{story.challenge}</p>
      <h2>The approach</h2>
      <p>{story.approach}</p>
      <h2>Where it landed</h2>
      <p>{story.outcome}</p>
      <div className="detail-services"><span>Engagement focus</span>{story.services.map((service) => <strong key={service}>{service}</strong>)}</div>
      <Link href="/contact" className="public-button public-button--dark">Start a similar project <ArrowRight size={15} /></Link>
    </div>
  </main>;
}

function ArticleDetailPage({ slug }: { slug: string }) {
  const article = articles.find((item) => slugify(item[1]) === slug) || articles[0];
  const story = articleStories[article[1]] || articleStories[articles[0][1]];
  return <main className="public-interior detail-page article-page">
    <div className="section-kicker">ERDEN MEDIA / {article[0]}</div>
    <h1>{article[1]}</h1>
    <p className="interior-lede">{article[2]}</p>
    <div className="detail-story article-story">
      <p className="article-intro">{story.intro}</p>
      {story.sections.map(([heading, paragraph]) => <section key={heading}><h2>{heading}</h2><p>{paragraph}</p></section>)}
      <p className="article-closing">{story.closing}</p>
      <Link href="/contact" className="public-button public-button--dark">Talk to EARDEN MEDIA <ArrowRight size={15} /></Link>
    </div>
  </main>;
}
